apache2_remove_default: yes
apache2_ports: [8080]
apache2_sites:
  - id: books
    state: present
    name: books.example.com
    port: 8080
    add_webroot: yes

mysql_db: "wordpress"
mysql_user: "wp_user"
mysql_pass: "wp_pass"

document_root: /var/www/books/htdocs # Apache2 role default site dir (/var/www) + Apache2 role site id (books) + htdocs
wp_owner: vagrant
wp_version: 5.7
wp_admin_name: admin
wp_admin_pass: pass

nginx_port: 80